[package]
name = "flipper-ir-dumps-vis"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
color-eyre = "0.6.3"
nom = "7.1.3"
plotters = "0.3.7"

[dev-dependencies]
indoc = "2.0.5"
