[package]
name = "flipper-ir-dumps-csv"
version = "0.0.0"
edition = "2021"

[dependencies]
flipper-ir-dumps = { path = "../flipper-ir-dumps" }
flipper-utils = { path = "../flipper-utils" }

clap.workspace = true
color-eyre.workspace = true
csv = "1.3.1"
